name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION: Hive.sln
      UNIT_TESTS: ./tests/Application.UnitTests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $SOLUTION
    - name: Build
      run: dotnet build --no-restore $SOLUTION
    - name: Test
      run: dotnet test --no-build --verbosity normal UNIT_TESTS
